@startchen

entity User {
  UserID : INTEGER <<key>>
  Login : STRING
  Password : STRING
  FullName {
    FirstName : STRING
    LastName : STRING
    Surname : STRING
  }
  Role : INTEGER
}

entity CinemaSession {
  SessionID : INTEGER <<key>>
  FilmID : INTEGER
  СinemaHallID : INTEGER
  ShowingTime : DATE
  SpectatorsCount : INTEGER
}

entity Film {
  FilmID : INTEGER <<key>>
  Name : STRING
  Duration : REAL
  GenreID : INTEGER
  Price : REAL
}

entity Genre {
  GenreID : INTEGER <<key>>
  Name : STRING
}

entity Ticket {
  TicketID : INTEGER <<key>>
  SessionID : INTEGER
  UserID : INTEGER
}

entity СinemaHall {
  СinemaHallID : INTEGER <<key>>
  Name : STRING
  Capacity : INTEGER
  VIPScalingPercent : INTEGER
}

entity Log {
  LogID : INTEGER <<key>>
  UserID : INTEGER
  ActionTime : DATE
  Action : STRING
}

relationship SELL {
}

relationship SHOW {
}

relationship WRITE {
}

relationship LOCATE {
}

relationship REFERS_TO {
}

' User sell many tickets
' Tickets can be sold by one user
SELL -1- User
SELL -N- Ticket

' Log was writen by concrete user
' Many users write log
WRITE -1- User
WRITE -N- Log


' Film can be showed on many sessions
' Concrete session show concrete film
SHOW -1- Film
SHOW -N- CinemaSession

' Cinema hall can locate many cinema sessions
' Cinema session locate in concrete hall
LOCATE -1- СinemaHall 
LOCATE -N- CinemaSession

' Concrete genre can have many films
' Film reffers to concrete genre
REFERS_TO -1- Genre
REFERS_TO -N- Film

@endchen
